CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255),
    nickname VARCHAR(255),
    full_name VARCHAR(255),
    is_public BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profession VARCHAR(255),
    expected_salary DOUBLE PRECISION,
    contact_email VARCHAR(255),
    phone VARCHAR(255),
    city VARCHAR(255),
    citizenship VARCHAR(255),
    birth_date VARCHAR(255),
    user_id VARCHAR(255) UNIQUE,
    CONSTRAINT fk_cvs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS cv_skills (
    cv_id BIGINT NOT NULL,
    skill VARCHAR(255),
    CONSTRAINT fk_cv_skills_cv FOREIGN KEY (cv_id) REFERENCES cvs(id)
);

CREATE TABLE IF NOT EXISTS experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(255),
    position VARCHAR(255),
    period VARCHAR(255),
    cv_id BIGINT,
    CONSTRAINT fk_experience_cv FOREIGN KEY (cv_id) REFERENCES cvs(id)
);

CREATE TABLE IF NOT EXISTS education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution VARCHAR(255),
    profession VARCHAR(255),
    degree VARCHAR(255),
    education_year VARCHAR(255),
    cv_id BIGINT,
    CONSTRAINT fk_education_cv FOREIGN KEY (cv_id) REFERENCES cvs(id)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    image_url VARCHAR(255),
    github_url VARCHAR(255),
    live_url VARCHAR(255),
    role VARCHAR(255),
    stack_summary VARCHAR(255),
    project_type VARCHAR(255),
    status VARCHAR(255),
    started_at DATE,
    finished_at DATE,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    user_id VARCHAR(255),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    issued_by VARCHAR(255),
    image_url VARCHAR(255),
    file_url VARCHAR(255),
    issue_date VARCHAR(255),
    description VARCHAR(255),
    city VARCHAR(255),
    place VARCHAR(255),
    event_name VARCHAR(255),
    event_type VARCHAR(255),
    importance INTEGER NOT NULL DEFAULT 0,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    user_id VARCHAR(255),
    CONSTRAINT fk_certificates_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(140) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_notifications_user_type UNIQUE (user_id, type)
);

CREATE TABLE IF NOT EXISTS portfolio_analytics (
    user_id VARCHAR(128) PRIMARY KEY,
    public_views BIGINT NOT NULL DEFAULT 0,
    share_clicks BIGINT NOT NULL DEFAULT 0,
    project_detail_views BIGINT NOT NULL DEFAULT 0,
    certificate_file_opens BIGINT NOT NULL DEFAULT 0,
    cv_downloads BIGINT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_analytics_monthly (
    user_id VARCHAR(128) NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    event_count BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, month_key),
    CONSTRAINT fk_portfolio_analytics_monthly_owner FOREIGN KEY (user_id) REFERENCES portfolio_analytics(user_id)
);
