export const citySuggestions = [
  'Astana',
  'Almaty',
  'Shymkent',
  'Karaganda',
  'Aktobe',
  'Atyrau',
  'Pavlodar',
  'Taraz',
  'Kostanay',
  'Ust-Kamenogorsk',
  'Oral',
  'Kyzylorda',
];

export const professionSuggestions = [
  'Backend Junior Developer',
  'Backend Middle Developer',
  'Backend Senior Developer',
  'Frontend Junior Developer',
  'Frontend Middle Developer',
  'Frontend Senior Developer',
  'Fullstack Developer',
  'Data Engineer',
  'DevOps Engineer',
  'Mobile Developer',
  'QA Engineer',
  'Product Manager',
];

export const skillSuggestions = [
  'Java',
  'Kotlin',
  'Go',
  'Python',
  'JavaScript',
  'TypeScript',
  'C#',
  'C++',
  'PHP',
  'Ruby',
  'SQL',
  'Bash',
  'Spring Boot',
  'Spring Security',
  'Hibernate',
  'JPA',
  'Micronaut',
  'NestJS',
  'Express.js',
  'FastAPI',
  'Django',
  'Flask',
  'ASP.NET Core',
  'PostgreSQL',
  'MySQL',
  'MSSQL',
  'Oracle DB',
  'MongoDB',
  'Redis',
  'Elasticsearch',
  'Kafka',
  'RabbitMQ',
  'React',
  'Next.js',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Tailwind CSS',
  'Redux Toolkit',
  'Zustand',
  'Vite',
  'Node.js',
  'GraphQL',
  'REST API',
  'gRPC',
  'WebSocket',
  'Docker',
  'Docker Compose',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'CI/CD',
  'GitHub Actions',
  'GitLab CI',
  'Jenkins',
  'Terraform',
  'Ansible',
  'Git',
  'Linux',
  'Nginx',
  'Maven',
  'Gradle',
  'Jest',
  'Vitest',
  'Cypress',
  'Playwright',
  'Postman',
  'Swagger/OpenAPI',
  'Figma',
  'Jira',
];

export const positionSuggestions = [
  'Backend Junior Developer',
  'Backend Middle Developer',
  'Backend Senior Developer',
  'Frontend Junior Developer',
  'Frontend Middle Developer',
  'Frontend Senior Developer',
  'Fullstack Developer',
  'Team Lead',
  'Engineering Manager',
];

export const universitySuggestions = [
  'Nazarbayev University',
  'Kazakh-British Technical University',
  'Al-Farabi Kazakh National University',
  'Satbayev University',
  'Astana IT University',
  'SDU University',
  'ENU L.N. Gumilyov',
  'IITU',
];

export const degreeSuggestions = [
  'Computer Science',
  'Software Engineering',
  'Information Systems',
  'Cybersecurity',
  'Data Science',
];

export const skillLevels = ['Basic', 'Weak', 'Medium', 'Advanced', 'Very high'] as const;
export type SkillLevel = (typeof skillLevels)[number];
